# Generated by Django 4.1 on 2022-08-22 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superhero_name', models.CharField(max_length=20)),
                ('has_comics', models.BooleanField()),
                ('has_toys', models.BooleanField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('ages', models.CharField(max_length=20)),
                ('super_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.superhero')),
            ],
        ),
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=20)),
                ('issue', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.publisher')),
                ('superhero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.superhero')),
            ],
        ),
    ]
