# Generated by Django 4.1 on 2022-08-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toys',
            old_name='name',
            new_name='toy_name',
        ),
    ]
