# Generated by Django 4.1 on 2022-08-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_toys_toy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='toys',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.publisher'),
            preserve_default=False,
        ),
    ]
